# Generated by Django 4.0 on 2024-09-10 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company/Industry Name')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area/Domain')),
                ('url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Company Link/URL')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('force_override', models.BooleanField(default=False, verbose_name='Force Override Email Validation')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
